#!/bin/sh
# Run one probe against the commit before the change, its head, and optionally
# released versions. Usage: run.sh <GROUP> [release ...]
# Scratch layout (deleted after the session): $S/base, $S/head are git worktrees
# of the two commits; $S/rel/<version> holds an unpacked PyPI wheel; $S/venv is
# the interpreter with the pinned dependencies; $S/certs holds the certificates.
set -u
S="${PROBE_SCRATCH:-<scratch>}"
here="$(cd "$(dirname "$0")" && pwd)"
group="$1"; shift
dir="$here/../$group"
export PROBE_CERTS="$S/certs" PROBE_SCRATCH="$S"
unset REQUESTS_CA_BUNDLE CURL_CA_BUNDLE SSL_CERT_FILE SSL_CERT_DIR
unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY all_proxy ALL_PROXY no_proxy NO_PROXY

run() { # label source-dir output
  PROBE_LABEL="$1" PYTHONPATH="$2:$here" "$S/venv/bin/python" -W ignore "$dir/probe.py" > "$3" 2>&1
  echo "== $group $1 (exit $?)"; cat "$3"
}
run "base 8dd3b26b (before the change)" "$S/base/src" "$dir/result-base.txt"
run "head 4089f3dc (the change)" "$S/head/src" "$dir/result-head.txt"
for version in "$@"; do
  run "release $version (PyPI wheel)" "$S/rel/$version" "$dir/result-release-$version.txt"
done
{
  echo "date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "os: $(uname -srm)"
  "$S/venv/bin/python" -c "import sys,ssl;print('python:',sys.version.replace(chr(10),' '));print('openssl (python ssl):',ssl.OPENSSL_VERSION)"
  echo "openssl cli: $(openssl version)"
  echo "uv: $(uv --version)"
  echo "installed in the probe environment:"
  uv pip freeze --python "$S/venv/bin/python" | sed 's/^/  /'
  echo "requests under test: source trees of base 8dd3b26bf59808de24fd654699f592abf6de581e and head 4089f3dc65f783beaa53cc032958ab625440d0ac from the local mirror, put first on PYTHONPATH"
  [ $# -gt 0 ] && echo "released versions also run (unpacked PyPI wheels, same dependencies): $*"
  echo "certificates: throwaway, generated by ../_common/make_certs.sh"
} > "$dir/environment.txt"
